basket-this-time/config/routes.rb
Rails.application.routes.draw do
  get 'page/home'

  root to: "page#home" 
  get 'order_items/create'

  get 'order_items/update'

  get 'order_items/destroy'

  get 'carts/show'

  "orders#update_status"

  resources :products, only: [:index]
  resource :cart, only: [:show]
  resources :order_items, only: [:create, :update, :destroy]

  get 'signup/' => 'users#new', as: :new_user
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  resources :orders, only: [:show]
  resources :users, except: [:new]
  resources :checkout, only: [:new, :create, :show]
  

end

basket-this-time/app/views/layouts/_cart_text.html.erb
<div class="text-center">
	<div class="row">
		<div class="col-xs-6 col-xs-offset-3">
			<center>
			<%= link_to "#{current_order.order_items.size} Items in Cart ", cart_path, class: "btn btn-link" %>
			</center>
		</div>	
	</div>
</div>

basket-this-time/app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
	<ul class="nav navbar-nav">
	<li><%#= link_to "Users", users_path %></li>
	<li><%#= link_to "Orders", orders_path %></li>
	<li><%#= link_to "Products", products_path %></li>
	</ul>
</nav>

basket-this-time/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BasketThisTime</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%#= render 'layouts/navbar' %>

<% if current_user.nil? %>

<% else %>
	<%= current_user.name %>
<% end %>

<div class="well">
<h1 class="cart-text"><%= render 'layouts/cart_text' %></h1>
 --> </div>



<%= yield %>


</body>
</html>