basket-this-time/config/routes.rb
Rails.application.routes.draw do
  get 'page/home'

  root to: "page#home" 
  get 'order_items/create'

  get 'order_items/update'

  get 'order_items/destroy'

  get 'carts/show'

  "orders#update_status"

  resources :products, only: [:index]
  resource :cart, only: [:show]
  resources :order_items, only: [:create, :update, :destroy]

  get 'signup/' => 'users#new', as: :new_user
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  resources :orders, only: [:show]
  resources :users, except: [:new]
  resources :checkout, only: [:new, :create, :show]
  

end

basket-this-time/app/models/user.rb
class User < ActiveRecord::Base
	has_many :orders
end

basket-this-time/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])
    @orders = @user.orders.where(user_id: @user.id)
    
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        # UserMailer.welcome_email(@user).deliver_now
        # HardWorker.perform_async(@user, 5)
        session[:user_id] = @user.id.to_s
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    session[:user_id] = nil
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :password, :has_many)
    end
end

basket-this-time/app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.text_field :password %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

basket-this-time/app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Password</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.password %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

basket-this-time/app/views/users/show.html.erb
<p id="notice"><%= notice %></p>
<div class="well">
	<div class="row">
		<div class="col-xs-6 col-xs-offset-3">
<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Password:</strong>
  <%= @user.password %>
</p>

<h4>Previous Orders</h4>
<<<<<<< HEAD
			<div>
				<% @orders.reverse.each do |order| %>
				<ul>
					<li>
						<%= link_to "Order Details", order_path(order) %>
						<%= order.id %>
						<strong><%= order.quantity %></strong>
						<%= order.total_price %>
					</li>
				</ul>
				<% end %>
			</div>
		</div>
	</div>	
=======
<div>
	<% @orders.reverse.each do |order| %>
	<ul>
		<li>
			<%= link_to "Order Details", order_path(order) %>
			<%= order.id %>
			<strong><%= order.quantity %></strong>
			<%= order.total_price %>
			<ul>
				<% order.order_items.each do |order_item|%>
					<li><%= order_item.product(:product_id).name %></li>
				<% end %>
			</ul>
		</li>
	</ul>
	<% end %>
>>>>>>> 20a437e6b9206876623260f79910b78c32354eb2
</div>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>