basket-this-time/config/routes.rb
Rails.application.routes.draw do
  get 'page/home'

  root to: "page#home" 
  get 'order_items/create'

  get 'order_items/update'

  get 'order_items/destroy'

  get 'carts/show'

  "orders#update_status"

  resources :products, only: [:index]
  resource :cart, only: [:show]
  resources :order_items, only: [:create, :update, :destroy]

  get 'signup/' => 'users#new', as: :new_user
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  resources :orders, only: [:show]
  resources :users, except: [:new]
  resources :checkout, only: [:new, :create, :show]
  

end

basket-this-time/app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :user
  belongs_to :order_status
  has_many :order_items, dependent: :destroy
  has_many :products


private
  def set_order_status
  	self.order_status_id = 1
  end
end

basket-this-time/app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]

  # GET /orders

  def index
  end

  # GET /orders/1

  def show
    @order = current_order
    @order_items = OrderItem.all
  end

  def update_status
    @order = current_order
    @order_items = OrderItem.all
    @order.order_status_id = 2
    if @order.save
      redirect_to order_path(@order)
    else
      redirect_to cart_path
    end
  end

  # GET /orders/new
  def new
  end


  def edit
  end


  def create
  end

  def update
    @order = current_order
    @order.update_attribute(order_status_id)
  end

  def destroy
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(:user_id, :total_price, :quantity)
    end
end

basket-this-time/app/helpers/orders_helper.rb
module OrdersHelper
	
end

basket-this-time/app/views/orders/_form.html.erb
<%= form_for(@order) do |f| %>
  <% if @order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
      <% @order.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id, value: current_user.id %>
  </div>
  <div class="field">
    <%= f.label :total_price %><br>
    <%= f.text_field :total_price %>
  </div>
  <div class="field">
    <%= f.label :quantity %><br>
    <%= f.text_field :quantity %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

basket-this-time/app/views/orders/edit.html.erb
<h1>Editing Order</h1>

<%= render 'form' %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

basket-this-time/app/views/orders/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Orders</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Total price</th>
      <th>Quantity</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td><%= order.user %></td>
        <td><%= order.total_price %></td>
        <td><%= order.quantity %></td>
        <td><%= link_to 'Show', order %></td>
        <td><%= link_to 'Edit', edit_order_path(order) %></td>
        <td><%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Order', new_order_path %>

basket-this-time/app/views/orders/new.html.erb
 <h1>New Order</h1>

<%= render 'form' %>

<%= link_to 'Back', orders_path %>

basket-this-time/app/views/orders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%=link_to "#{@order.user.name}", user_path(@order.user) %>
</p>

<p>
  <strong>Total price:</strong>
  <%= @order.total_price %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @order.quantity %>
</p>

<div>

<% if @order.order_status_id == 1 %>
<h1>In Progress Orders</h1>
	<% @order_items.each do |oi| %>
		<ul>
			<li><strong><%= oi.product.name %></strong> <%= oi.product.description %>
			</li>
		</ul>	
	<% end %>
<% end %>
<% if @order.order_status_id == 2 %>
	<% @order_items.each do |oi| %>
		<ul>
			<li><strong><%= oi.product.name %></strong> <%= oi.product.description %>
			</li>
		</ul>	
	<% end %>
<% end %>
</div>